# Generated by Django 5.2.12 on 2026-03-20 19:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restaurante_id', models.UUIDField()),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
                'ordering': ['restaurante_id', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restaurante_id', models.UUIDField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente'), ('ENVIADA', 'Enviada'), ('RECIBIDA', 'Recibida'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20)),
                ('moneda', models.CharField(choices=[('COP', 'Peso colombiano'), ('USD', 'Dólar estadounidense'), ('EUR', 'Euro'), ('MXN', 'Peso mexicano'), ('ARS', 'Peso argentino'), ('BRL', 'Real brasileño'), ('CLP', 'Peso chileno')], default='USD', max_length=10)),
                ('total_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega_estimada', models.DateTimeField(blank=True, null=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=100)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('moneda_preferida', models.CharField(choices=[('COP', 'Peso colombiano'), ('USD', 'Dólar estadounidense'), ('EUR', 'Euro'), ('MXN', 'Peso mexicano'), ('ARS', 'Peso argentino'), ('BRL', 'Real brasileño'), ('CLP', 'Peso chileno')], default='USD', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='LoteIngrediente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ingrediente_id', models.UUIDField()),
                ('numero_lote', models.CharField(max_length=100)),
                ('fecha_produccion', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField()),
                ('cantidad_recibida', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cantidad_actual', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramo'), ('g', 'Gramo'), ('l', 'Litro'), ('ml', 'Mililitro'), ('und', 'Unidad'), ('por', 'Porción')], max_length=10)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('AGOTADO', 'Agotado'), ('VENCIDO', 'Vencido'), ('RETIRADO', 'Retirado')], default='ACTIVO', max_length=20)),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='inventory.almacen')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='inventory.proveedor')),
            ],
            options={
                'verbose_name': 'Lote de Ingrediente',
                'verbose_name_plural': 'Lotes de Ingrediente',
                'ordering': ['fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='IngredienteInventario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ingrediente_id', models.UUIDField()),
                ('nombre_ingrediente', models.CharField(max_length=255)),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramo'), ('g', 'Gramo'), ('l', 'Litro'), ('ml', 'Mililitro'), ('und', 'Unidad'), ('por', 'Porción')], max_length=10)),
                ('cantidad_actual', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('nivel_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('nivel_maximo', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='inventory.almacen')),
                ('lote_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='en_uso', to='inventory.loteingrediente')),
            ],
            options={
                'verbose_name': 'Ingrediente en Inventario',
                'verbose_name_plural': 'Ingredientes en Inventario',
            },
        ),
        migrations.CreateModel(
            name='AlertaStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restaurante_id', models.UUIDField()),
                ('ingrediente_id', models.UUIDField()),
                ('tipo_alerta', models.CharField(choices=[('STOCK_BAJO', 'Stock bajo mínimo'), ('VENCIMIENTO', 'Lote próximo a vencer'), ('AGOTADO', 'Ingrediente agotado')], max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RESUELTA', 'Resuelta'), ('IGNORADA', 'Ignorada')], default='PENDIENTE', max_length=20)),
                ('nivel_actual', models.DecimalField(decimal_places=3, max_digits=10)),
                ('nivel_minimo', models.DecimalField(decimal_places=3, max_digits=10)),
                ('fecha_alerta', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='inventory.almacen')),
                ('ingrediente_inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='inventory.ingredienteinventario')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='inventory.loteingrediente')),
            ],
            options={
                'verbose_name': 'Alerta de Stock',
                'verbose_name_plural': 'Alertas de Stock',
                'ordering': ['-fecha_alerta'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada — lote recibido'), ('SALIDA', 'Salida — pedido confirmado'), ('DEVOLUCION', 'Devolución — pedido cancelado'), ('AJUSTE', 'Ajuste manual'), ('VENCIMIENTO', 'Vencimiento de lote')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cantidad_antes', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cantidad_despues', models.DecimalField(decimal_places=3, max_digits=10)),
                ('pedido_id', models.UUIDField(blank=True, null=True)),
                ('orden_compra_id', models.UUIDField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ingrediente_inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventory.ingredienteinventario')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='inventory.loteingrediente')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenCompra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ingrediente_id', models.UUIDField()),
                ('nombre_ingrediente', models.CharField(max_length=255)),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramo'), ('g', 'Gramo'), ('l', 'Litro'), ('ml', 'Mililitro'), ('und', 'Unidad'), ('por', 'Porción')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cantidad_recibida', models.DecimalField(decimal_places=3, default=0, help_text='Se actualiza al recibir la orden — puede ser menor a la pedida.', max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventory.ordencompra')),
            ],
            options={
                'verbose_name': 'Detalle de Orden de Compra',
                'verbose_name_plural': 'Detalles de Orden de Compra',
            },
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='inventory.proveedor'),
        ),
        migrations.CreateModel(
            name='RecetaPlato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plato_id', models.UUIDField()),
                ('ingrediente_id', models.UUIDField()),
                ('nombre_ingrediente', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramo'), ('g', 'Gramo'), ('l', 'Litro'), ('ml', 'Mililitro'), ('und', 'Unidad'), ('por', 'Porción')], max_length=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Receta de Plato',
                'verbose_name_plural': 'Recetas de Plato',
                'constraints': [models.UniqueConstraint(fields=('plato_id', 'ingrediente_id'), name='unique_receta_plato_ingrediente')],
            },
        ),
        migrations.AddConstraint(
            model_name='ingredienteinventario',
            constraint=models.UniqueConstraint(fields=('ingrediente_id', 'almacen'), name='unique_ingrediente_almacen'),
        ),
    ]
