# Generated by Django 5.2.12 on 2026-03-31 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetaplato',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Precio pagado al proveedor por unidad. Se actualiza al recibir una orden de compra.', max_digits=10),
        ),
        migrations.AddField(
            model_name='recetaplato',
            name='fecha_costo_actualizado',
            field=models.DateTimeField(blank=True, help_text='Última vez que se actualizó el costo desde una orden de compra.', null=True),
        ),
    ]
