# Generated by Django 5.2.13 on 2026-04-08 08:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_recetaplato_costo_unitario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('ingrediente_id', models.UUIDField(db_index=True,
                 help_text='UUID del ingrediente en menu_service', unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramo'), ('g', 'Gramo'), ('l', 'Litro'), (
                    'ml', 'Mililitro'), ('und', 'Unidad'), ('por', 'Porción')], default='und', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ingrediente (caché)',
                'verbose_name_plural': 'Ingredientes (caché)',
                'ordering': ['nombre'],
            },
        ),
    ]
