# Generated by Django 5.2.13 on 2026-04-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_ingrediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='alcance',
            field=models.CharField(choices=[('GLOBAL', 'Global — visible para todos los restaurantes'), ('PAIS', 'País — visible para restaurantes del país indicado'), ('CIUDAD', 'Ciudad — visible para restaurantes de esa ciudad'), ('LOCAL', 'Local — solo el restaurante que lo creó')], default='GLOBAL', help_text='Opción B: controla qué restaurantes pueden ver este proveedor.', max_length=10),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='ciudad_destino',
            field=models.CharField(blank=True, help_text='Requerido si alcance=CIUDAD.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='creado_por_restaurante_id',
            field=models.UUIDField(blank=True, help_text='UUID del restaurante que creó este proveedor. Solo para alcance=LOCAL.', null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='pais_destino',
            field=models.CharField(blank=True, help_text='Requerido si alcance=PAIS o alcance=CIUDAD.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recetaplato',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Precio pagado al proveedor por unidad.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='recetaplato',
            name='fecha_costo_actualizado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
