# Generated by Django 5.2.13 on 2026-04-12 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='restaurante',
            field=models.ForeignKey(blank=True, help_text='null = global (toda la cadena). Asignado = exclusivo de ese restaurante.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='menu.restaurante'),
        ),
        migrations.AddField(
            model_name='plato',
            name='restaurante',
            field=models.ForeignKey(blank=True, help_text='null = global. Asignado = exclusivo de ese restaurante.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platos', to='menu.restaurante'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='ingrediente',
            constraint=models.UniqueConstraint(fields=('nombre', 'restaurante'), name='unique_ingrediente_nombre_restaurante'),
        ),
    ]
