# Generated by Django 5.2.13 on 2026-05-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_ingrediente_restaurante_plato_restaurante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='imagen',
            field=models.URLField(blank=True, default='', help_text='URL pública de la foto del restaurante (Cloudinary, S3, Imgur, etc.). Vacía = el frontend usa un placeholder.', max_length=500),
        ),
    ]
