# Generated by Django 5.2.1 on 2026-05-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_restaurante_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='moneda',
            field=models.CharField(choices=[('COP', 'Peso colombiano'), ('USD', 'Dólar estadounidense'), ('EUR', 'Euro'), ('MXN', 'Peso mexicano'), ('ARS', 'Peso argentino'), ('BRL', 'Real brasileño'), ('CLP', 'Peso chileno'), ('PEN', 'Sol peruano'), ('BOB', 'Boliviano'), ('VES', 'Bolívar venezolano')], default='COP', max_length=10),
        ),
    ]
