# Generated by Django 5.2.12 on 2026-03-18 03:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restaurante_id', models.UUIDField()),
                ('cliente_id', models.UUIDField(blank=True, null=True)),
                ('canal', models.CharField(choices=[('TPV', 'TPV Presencial'), ('APP', 'App Cliente'), ('UBER_EATS', 'Uber Eats'), ('RAPPI', 'Rappi')], default='TPV', max_length=20)),
                ('estado', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_PREPARACION', 'En Preparación'), ('LISTO', 'Listo'), ('EN_CAMINO', 'En Camino'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='RECIBIDO', max_length=20)),
                ('prioridad', models.IntegerField(choices=[(1, 'Baja'), (2, 'Normal'), (3, 'Alta'), (4, 'Urgente')], default=2)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(max_length=10)),
                ('mesa_id', models.UUIDField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega_estimada', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-prioridad', 'fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EntregaPedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_entrega', models.CharField(choices=[('LOCAL', 'En Local'), ('PICKUP', 'Pickup'), ('DELIVERY', 'Delivery')], default='LOCAL', max_length=20)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('repartidor_id', models.UUIDField(blank=True, null=True)),
                ('repartidor_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_entrega', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_CAMINO', 'En Camino'), ('ENTREGADO', 'Entregado'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=20)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrega', to='orders.pedido')),
            ],
            options={
                'verbose_name': 'Entrega de Pedido',
                'verbose_name_plural': 'Entregas de Pedido',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plato_id', models.UUIDField()),
                ('nombre_plato', models.CharField(max_length=255)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notas', models.TextField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='orders.pedido')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedido',
            },
        ),
        migrations.CreateModel(
            name='ComandaCocina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estacion', models.CharField(choices=[('PARRILLA', 'Parrilla'), ('BEBIDAS', 'Bebidas'), ('POSTRES', 'Postres'), ('FRIOS', 'Fríos'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PREPARANDO', 'Preparando'), ('LISTO', 'Listo')], default='PENDIENTE', max_length=20)),
                ('hora_envio', models.DateTimeField(auto_now_add=True)),
                ('hora_fin', models.DateTimeField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comandas', to='orders.pedido')),
            ],
            options={
                'verbose_name': 'Comanda de Cocina',
                'verbose_name_plural': 'Comandas de Cocina',
            },
        ),
        migrations.CreateModel(
            name='SeguimientoPedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_PREPARACION', 'En Preparación'), ('LISTO', 'Listo'), ('EN_CAMINO', 'En Camino'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='orders.pedido')),
            ],
            options={
                'verbose_name': 'Seguimiento de Pedido',
                'verbose_name_plural': 'Seguimientos de Pedido',
                'ordering': ['fecha'],
            },
        ),
    ]
