# Generated by Django 5.2.13 on 2026-04-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_pedido_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='numero_dia',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
