# Generated by Django 5.2.14 on 2026-05-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_pedido_numero_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='total_cobrado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total real cobrado tras aplicar cupones/puntos. null = sin descuentos.', max_digits=10, null=True),
        ),
    ]
