# Generated by Django 5.2.12 on 2026-03-22 00:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoCategoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoria_id', models.UUIDField(db_index=True, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catálogo de categoría',
                'verbose_name_plural': 'Catálogo de categorías',
            },
        ),
        migrations.CreateModel(
            name='CatalogoPlato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plato_id', models.UUIDField(db_index=True, unique=True)),
                ('categoria_id', models.UUIDField(blank=True, db_index=True, help_text='UUID de la categoría en menu_service', null=True)),
                ('nombre', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catálogo de plato',
                'verbose_name_plural': 'Catálogo de platos',
            },
        ),
        migrations.CreateModel(
            name='CuentaPuntos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cliente_id', models.UUIDField(db_index=True, unique=True)),
                ('saldo', models.PositiveIntegerField(default=0, help_text='Puntos disponibles actualmente')),
                ('puntos_totales_historicos', models.PositiveIntegerField(default=0, help_text='Total de puntos acumulados en toda la historia (nunca decrece)')),
                ('nivel', models.CharField(choices=[('bronce', 'Bronce'), ('plata', 'Plata'), ('oro', 'Oro'), ('diamante', 'Diamante')], default='bronce', help_text='Nivel determinado por puntos_totales_historicos', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cuenta de puntos',
                'verbose_name_plural': 'Cuentas de puntos',
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('alcance', models.CharField(choices=[('global', 'Global (toda la cadena)'), ('marca', 'Por marca'), ('local', 'Por restaurante')], max_length=10)),
                ('marca', models.CharField(blank=True, help_text='Nombre de la marca — requerido si alcance=MARCA', max_length=100)),
                ('restaurante_id', models.UUIDField(blank=True, db_index=True, help_text='UUID del restaurante — requerido si alcance=LOCAL', null=True)),
                ('tipo_beneficio', models.CharField(choices=[('descuento_pct', 'Descuento porcentual'), ('descuento_monto', 'Descuento en monto fijo'), ('puntos_extra', 'Puntos extra'), ('regalo', 'Producto de regalo'), ('2x1', '2x1')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, default=0, help_text='Valor del descuento (monto o porcentaje según tipo_beneficio)', max_digits=10)),
                ('puntos_bonus', models.PositiveIntegerField(default=0, help_text='Puntos extra a otorgar — aplica cuando tipo_beneficio=PUNTOS_EXTRA')),
                ('multiplicador_puntos', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplicador sobre los puntos base del pedido (ej: 2.0 = doble puntos)', max_digits=4)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['activa', 'fecha_inicio', 'fecha_fin'], name='loyalty_pro_activa_547a8e_idx'), models.Index(fields=['alcance', 'activa'], name='loyalty_pro_alcance_66de07_idx')],
            },
        ),
        migrations.CreateModel(
            name='AplicacionPromocion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pedido_id', models.UUIDField(db_index=True, unique=True)),
                ('cliente_id', models.UUIDField(db_index=True)),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, default=0, help_text='Monto de descuento aplicado al pedido', max_digits=12)),
                ('puntos_bonus_otorgados', models.PositiveIntegerField(default=0, help_text='Puntos bonus otorgados por esta promoción')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='loyalty.promocion')),
            ],
            options={
                'verbose_name': 'Aplicación de promoción',
                'verbose_name_plural': 'Aplicaciones de promoción',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='ReglaPromocion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_condicion', models.CharField(choices=[('monto_minimo', 'Monto mínimo de compra'), ('plato', 'Plato específico'), ('categoria', 'Categoría de plato'), ('hora', 'Franja horaria'), ('primer_pedido', 'Primer pedido del cliente')], max_length=20)),
                ('monto_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('moneda', models.CharField(blank=True, choices=[('COP', 'Peso colombiano'), ('USD', 'Dólar estadounidense'), ('EUR', 'Euro'), ('MXN', 'Peso mexicano'), ('ARS', 'Peso argentino'), ('BRL', 'Real brasileño'), ('CLP', 'Peso chileno')], help_text='Moneda del monto mínimo', max_length=3)),
                ('plato_id', models.UUIDField(blank=True, db_index=True, help_text='UUID del plato en menu_service', null=True)),
                ('categoria_id', models.UUIDField(blank=True, db_index=True, help_text='UUID de la categoría en menu_service', null=True)),
                ('hora_inicio', models.PositiveSmallIntegerField(blank=True, help_text='Hora de inicio en formato 0-23 (ej: 11 = 11:00)', null=True)),
                ('hora_fin', models.PositiveSmallIntegerField(blank=True, help_text='Hora de fin en formato 0-23 (ej: 14 = 14:00)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas', to='loyalty.promocion')),
            ],
            options={
                'verbose_name': 'Regla de promoción',
                'verbose_name_plural': 'Reglas de promoción',
            },
        ),
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cliente_id', models.UUIDField(blank=True, db_index=True, help_text='UUID del cliente — nulo si el cupón es genérico', null=True)),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('tipo_descuento', models.CharField(choices=[('porcentaje', 'Porcentaje'), ('monto_fijo', 'Monto fijo')], max_length=10)),
                ('valor_descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limite_uso', models.PositiveSmallIntegerField(default=1, help_text='Cantidad máxima de veces que puede usarse')),
                ('usos_actuales', models.PositiveSmallIntegerField(default=0)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promocion', models.ForeignKey(blank=True, help_text='Promoción que originó este cupón — puede ser nulo si es manual', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cupones', to='loyalty.promocion')),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cliente_id', 'activo'], name='loyalty_cup_cliente_72a520_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransaccionPuntos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('acumulacion', 'Acumulación'), ('canje', 'Canje'), ('vencimiento', 'Vencimiento'), ('ajuste', 'Ajuste manual'), ('bono', 'Bono promocional')], max_length=15)),
                ('puntos', models.IntegerField(help_text='Positivo = acumulación/bono. Negativo = canje/vencimiento.')),
                ('saldo_anterior', models.PositiveIntegerField()),
                ('saldo_posterior', models.PositiveIntegerField()),
                ('pedido_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('restaurante_id', models.UUIDField(blank=True, null=True)),
                ('promocion_id', models.UUIDField(blank=True, help_text='Si la transacción es resultado de una promoción', null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='loyalty.cuentapuntos')),
            ],
            options={
                'verbose_name': 'Transacción de puntos',
                'verbose_name_plural': 'Transacciones de puntos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cuenta', 'tipo'], name='loyalty_tra_cuenta__66076f_idx'), models.Index(fields=['pedido_id'], name='loyalty_tra_pedido__5774f6_idx')],
            },
        ),
    ]
