# Generated by Django 5.2.13 on 2026-04-12 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_eventlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventLog',
        ),
    ]
