# Generated by Django 5.2.14 on 2026-05-26 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0003_delete_eventlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupon',
            name='restaurante_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='aplicacionpromocion',
            name='descuento_aplicado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='aplicacionpromocion',
            name='puntos_bonus_otorgados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='catalogoplato',
            name='categoria_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuentapuntos',
            name='nivel',
            field=models.CharField(choices=[('bronce', 'Bronce'), ('plata', 'Plata'), ('oro', 'Oro'), ('diamante', 'Diamante')], default='bronce', max_length=10),
        ),
        migrations.AlterField(
            model_name='cuentapuntos',
            name='puntos_totales_historicos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cuentapuntos',
            name='saldo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cupon',
            name='cliente_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cupon',
            name='limite_uso',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cupon',
            name='promocion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cupones', to='loyalty.promocion'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='multiplicador_puntos',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='puntos_bonus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='restaurante_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reglapromocion',
            name='categoria_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='reglapromocion',
            name='hora_fin',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reglapromocion',
            name='hora_inicio',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reglapromocion',
            name='moneda',
            field=models.CharField(blank=True, choices=[('COP', 'Peso colombiano'), ('USD', 'Dólar estadounidense'), ('EUR', 'Euro'), ('MXN', 'Peso mexicano'), ('ARS', 'Peso argentino'), ('BRL', 'Real brasileño'), ('CLP', 'Peso chileno')], max_length=3),
        ),
        migrations.AlterField(
            model_name='reglapromocion',
            name='plato_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaccionpuntos',
            name='promocion_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaccionpuntos',
            name='puntos',
            field=models.IntegerField(),
        ),
        migrations.AddIndex(
            model_name='cupon',
            index=models.Index(fields=['restaurante_id', 'activo'], name='loyalty_cup_restaur_f4429b_idx'),
        ),
    ]
