# Generated by Django 5.2.13 on 2026-05-07 02:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('NIT', 'NIT'), ('OT', 'Otro')], default='CC', max_length=5)),
                ('cedula', models.CharField(db_index=True, help_text='Número de documento de identidad.', max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.EmailField(blank=True, db_index=True, default='', max_length=254)),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('usuario_id', models.UUIDField(blank=True, db_index=True, help_text='UUID del Usuario de la app móvil. Si está vinculado, las ventas en tienda acreditan puntos al usuario.', null=True)),
                ('restaurante_id', models.UUIDField(blank=True, db_index=True, help_text='UUID del restaurante que registró al cliente. NULL = cliente global.', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre', 'apellido'],
            },
        ),
        migrations.RenameIndex(
            model_name='refreshtoken',
            new_name='auth_app_re_token_2c1e60_idx',
            old_name='auth_app_re_token_idx',
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='expira_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='expira_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['cedula'], name='cliente_cedula_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['email'], name='cliente_email_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['restaurante_id', 'cedula'], name='cliente_rest_cedula_idx'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('tipo_documento', 'cedula', 'restaurante_id'), name='unique_cliente_doc_restaurante'),
        ),
    ]
