# Generated by Django 5.2.13 on 2026-05-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin_central', 'Admin Central'), ('gerente_local', 'Gerente Local'), ('supervisor', 'Supervisor'), ('cocinero', 'Cocinero'), ('mesero', 'Mesero'), ('cajero', 'Cajero'), ('repartidor', 'Repartidor'), ('cliente', 'Cliente App')], default='mesero', max_length=20),
        ),
    ]
