# Generated by Django 5.2.14 on 2026-05-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='restaurante_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='usuario_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
