"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

# gateway_service/config/settings.py
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# ✅ SECRET_KEY desde env
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "dev-secret-key-gateway")

DEBUG = os.getenv("DEBUG", "True") == "True"

# ✅ ALLOWED_HOSTS correcto para Docker + desarrollo
ALLOWED_HOSTS = ["*"]

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "graphene_django",
    "corsheaders",
    "app.gateway",
]

GRAPHENE = {
    "SCHEMA": "app.gateway.graphql.schema.schema"
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:3000",
]
CORS_ALLOW_ALL_ORIGINS = DEBUG  # En desarrollo acepta todos

# ✅ Sin base de datos — el gateway no tiene modelos propios
# Solo necesita la DB para django.contrib.admin/auth/sessions
# que no usamos. Se usa sqlite en memoria para no generar archivo.
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": ":memory:",  # ✅ en memoria, no genera db.sqlite3
    }
}

LANGUAGE_CODE = "es-co"
TIME_ZONE = "America/Bogota"
USE_I18N = True
USE_TZ = True

STATIC_URL = "static/"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ─────────────────────────────────────────
# URLs de microservicios (override via env en Docker)
# ─────────────────────────────────────────
# Estos se leen en cada client module — aquí solo como referencia
# MENU_SERVICE_URL      = os.getenv("MENU_SERVICE_URL",      "http://menu_service:8000/api/menu")
# ORDER_SERVICE_URL     = os.getenv("ORDER_SERVICE_URL",     "http://order_service:8000/api/orders")
# INVENTORY_SERVICE_URL = os.getenv("INVENTORY_SERVICE_URL", "http://inventory_service:8000/api/inventory")
# STAFF_SERVICE_URL     = os.getenv("STAFF_SERVICE_URL",     "http://staff_service:8000/api/staff")
# LOYALTY_SERVICE_URL   = os.getenv("LOYALTY_SERVICE_URL",   "http://loyalty_service:8000/api/loyalty")
