# Generated by Django 5.2.12 on 2026-03-21 20:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionLaboralPais',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pais', models.CharField(choices=[('CO', 'Colombia'), ('MX', 'México'), ('AR', 'Argentina'), ('CL', 'Chile'), ('BR', 'Brasil'), ('PE', 'Perú'), ('PA', 'Panamá')], max_length=2, unique=True)),
                ('horas_max_diarias', models.PositiveSmallIntegerField(default=8, help_text='Horas máximas de trabajo por día')),
                ('horas_max_semanales', models.PositiveSmallIntegerField(default=48, help_text='Horas máximas de trabajo por semana')),
                ('factor_hora_extra', models.DecimalField(decimal_places=2, default=1.5, help_text='Multiplicador sobre el valor hora base (1.50 = 50% extra)', max_digits=4)),
                ('descanso_min_entre_turnos', models.PositiveSmallIntegerField(default=480, help_text='Minutos mínimos de descanso entre dos turnos consecutivos')),
                ('horas_continuas_para_descanso', models.PositiveSmallIntegerField(default=6, help_text='Horas continuas de trabajo que obligan una pausa')),
                ('duracion_descanso_obligatorio', models.PositiveSmallIntegerField(default=30, help_text='Duración en minutos de la pausa obligatoria')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración laboral por país',
                'verbose_name_plural': 'Configuraciones laborales por país',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('documento', models.CharField(help_text='Cédula o documento de identidad', max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('rol', models.CharField(choices=[('cocinero', 'Cocinero'), ('repartidor', 'Repartidor'), ('cajero', 'Cajero'), ('mesero', 'Mesero'), ('gerente', 'Gerente'), ('supervisor', 'Supervisor'), ('auxiliar', 'Auxiliar de cocina')], max_length=20)),
                ('pais', models.CharField(choices=[('CO', 'Colombia'), ('MX', 'México'), ('AR', 'Argentina'), ('CL', 'Chile'), ('BR', 'Brasil'), ('PE', 'Perú'), ('PA', 'Panamá')], help_text='Define qué ConfiguracionLaboralPais aplica', max_length=2)),
                ('fecha_contratacion', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='RestauranteLocal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restaurante_id', models.UUIDField(db_index=True, help_text='UUID del restaurante en menu_service', unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('pais', models.CharField(choices=[('CO', 'Colombia'), ('MX', 'México'), ('AR', 'Argentina'), ('CL', 'Chile'), ('BR', 'Brasil'), ('PE', 'Perú'), ('PA', 'Panamá')], max_length=2)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Restaurante local',
                'verbose_name_plural': 'Restaurantes locales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AlertaOperacional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restaurante_id', models.UUIDField(db_index=True)),
                ('tipo', models.CharField(choices=[('stock_bajo', 'Stock bajo'), ('agotado', 'Ingrediente agotado'), ('vencimiento', 'Vencimiento próximo'), ('orden_compra', 'Orden de compra')], max_length=20)),
                ('nivel', models.CharField(choices=[('info', 'Informativa'), ('urgente', 'Urgente'), ('critica', 'Crítica')], max_length=10)),
                ('mensaje', models.TextField()),
                ('referencia_id', models.UUIDField(blank=True, help_text='UUID del recurso que disparó la alerta (lote, ingrediente, orden)', null=True)),
                ('resuelta', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alerta operacional',
                'verbose_name_plural': 'Alertas operacionales',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['restaurante_id', 'resuelta'], name='staff_alert_restaur_6d35d8_idx'), models.Index(fields=['nivel', 'resuelta'], name='staff_alert_nivel_7090d8_idx')],
            },
        ),
        migrations.CreateModel(
            name='EstacionCocina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restaurante_id', models.UUIDField(db_index=True)),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad_simultanea', models.PositiveSmallIntegerField(default=1, help_text='Máximo de cocineros asignados en paralelo a esta estación')),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estación de cocina',
                'verbose_name_plural': 'Estaciones de cocina',
                'unique_together': {('restaurante_id', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='AsignacionCocina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pedido_id', models.UUIDField(db_index=True)),
                ('comanda_id', models.UUIDField(db_index=True, unique=True)),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
                ('sla_segundos', models.PositiveIntegerField(blank=True, help_text='Segundos reales desde asignación hasta completado. Calculado al cerrar.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cocinero', models.ForeignKey(limit_choices_to={'rol__in': ['cocinero', 'auxiliar']}, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_cocina', to='staff.empleado')),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='staff.estacioncocina')),
            ],
            options={
                'verbose_name': 'Asignación de cocina',
                'verbose_name_plural': 'Asignaciones de cocina',
                'ordering': ['-asignado_en'],
            },
        ),
        migrations.CreateModel(
            name='PrediccionPersonal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restaurante_id', models.UUIDField(db_index=True)),
                ('fecha', models.DateField()),
                ('demanda_estimada', models.PositiveIntegerField(help_text='Número de pedidos estimados para ese día')),
                ('personal_recomendado', models.PositiveSmallIntegerField(help_text='Cantidad de empleados sugeridos para cubrir la demanda')),
                ('fuente', models.CharField(choices=[('historial', 'Historial de pedidos'), ('estacional', 'Estacionalidad'), ('evento', 'Evento programado'), ('combinado', 'Combinado')], default='historial', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Predicción de personal',
                'verbose_name_plural': 'Predicciones de personal',
                'ordering': ['-fecha'],
                'unique_together': {('restaurante_id', 'fecha')},
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='staff.restaurantelocal'),
        ),
        migrations.CreateModel(
            name='ServicioEntrega',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pedido_id', models.UUIDField(db_index=True, unique=True)),
                ('estado', models.CharField(choices=[('asignada', 'Asignada'), ('en_camino', 'En camino'), ('completada', 'Completada'), ('fallida', 'Fallida')], default='asignada', max_length=20)),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repartidor', models.ForeignKey(limit_choices_to={'rol': 'repartidor'}, on_delete=django.db.models.deletion.PROTECT, related_name='servicios_entrega', to='staff.empleado')),
            ],
            options={
                'verbose_name': 'Servicio de entrega',
                'verbose_name_plural': 'Servicios de entrega',
                'ordering': ['-asignado_en'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restaurante_id', models.UUIDField(db_index=True, help_text='UUID snapshot del restaurante — no FK externa')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('activo', 'Activo'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='programado', max_length=20)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qr_expira_en', models.DateTimeField(blank=True, help_text='Hasta cuándo el QR es válido para registrar entrada', null=True)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='staff.empleado')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hora_entrada', models.DateTimeField()),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('metodo_registro', models.CharField(choices=[('qr', 'QR dinámico'), ('manual', 'Registro manual')], default='qr', max_length=10)),
                ('horas_normales', models.DecimalField(decimal_places=2, default=0, help_text='Horas dentro del límite diario del país', max_digits=5)),
                ('horas_extra', models.DecimalField(decimal_places=2, default=0, help_text='Horas por encima del límite diario', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('turno', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='registro_asistencia', to='staff.turno')),
            ],
            options={
                'verbose_name': 'Registro de asistencia',
                'verbose_name_plural': 'Registros de asistencia',
            },
        ),
        migrations.CreateModel(
            name='ResumenNomina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('total_horas_normales', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_horas_extra', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('dias_trabajados', models.PositiveSmallIntegerField(default=0)),
                ('moneda', models.CharField(choices=[('COP', 'Peso colombiano'), ('USD', 'Dólar estadounidense'), ('EUR', 'Euro'), ('MXN', 'Peso mexicano'), ('ARS', 'Peso argentino'), ('BRL', 'Real brasileño'), ('CLP', 'Peso chileno')], max_length=3)),
                ('cerrado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resumenes_nomina', to='staff.empleado')),
            ],
            options={
                'verbose_name': 'Resumen de nómina',
                'verbose_name_plural': 'Resúmenes de nómina',
                'ordering': ['-periodo_inicio'],
                'unique_together': {('empleado', 'periodo_inicio', 'periodo_fin')},
            },
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['restaurante_id', 'fecha_inicio'], name='staff_turno_restaur_a9eb83_idx'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['empleado', 'estado'], name='staff_turno_emplead_8e4119_idx'),
        ),
    ]
