# Generated by Django 5.2.13 on 2026-04-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionlaboralpais',
            name='pais',
            field=models.CharField(choices=[('CO', 'Colombia'), ('MX', 'México'), ('AR', 'Argentina'), ('CL', 'Chile'), ('BR', 'Brasil'), ('PE', 'Perú'), ('PA', 'Panamá'), ('US', 'Estados Unidos')], max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='pais',
            field=models.CharField(choices=[('CO', 'Colombia'), ('MX', 'México'), ('AR', 'Argentina'), ('CL', 'Chile'), ('BR', 'Brasil'), ('PE', 'Perú'), ('PA', 'Panamá'), ('US', 'Estados Unidos')], help_text='Define qué ConfiguracionLaboralPais aplica', max_length=2),
        ),
        migrations.AlterField(
            model_name='restaurantelocal',
            name='pais',
            field=models.CharField(choices=[('CO', 'Colombia'), ('MX', 'México'), ('AR', 'Argentina'), ('CL', 'Chile'), ('BR', 'Brasil'), ('PE', 'Perú'), ('PA', 'Panamá'), ('US', 'Estados Unidos')], max_length=2),
        ),
    ]
