# Generated by Django 5.2.14 on 2026-05-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_configuracionlaboralpais_pais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionlaboralpais',
            name='pais',
            field=models.CharField(choices=[('CO', 'Colombia'), ('MX', 'México'), ('AR', 'Argentina'), ('CL', 'Chile'), ('BR', 'Brasil'), ('PE', 'Perú'), ('PA', 'Panamá'), ('US', 'Estados Unidos'), ('ES', 'España'), ('BO', 'Bolivia'), ('VE', 'Venezuela')], max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='pais',
            field=models.CharField(choices=[('CO', 'Colombia'), ('MX', 'México'), ('AR', 'Argentina'), ('CL', 'Chile'), ('BR', 'Brasil'), ('PE', 'Perú'), ('PA', 'Panamá'), ('US', 'Estados Unidos'), ('ES', 'España'), ('BO', 'Bolivia'), ('VE', 'Venezuela')], help_text='Define qué ConfiguracionLaboralPais aplica', max_length=2),
        ),
        migrations.AlterField(
            model_name='restaurantelocal',
            name='pais',
            field=models.CharField(choices=[('CO', 'Colombia'), ('MX', 'México'), ('AR', 'Argentina'), ('CL', 'Chile'), ('BR', 'Brasil'), ('PE', 'Perú'), ('PA', 'Panamá'), ('US', 'Estados Unidos'), ('ES', 'España'), ('BO', 'Bolivia'), ('VE', 'Venezuela')], max_length=2),
        ),
        migrations.AlterField(
            model_name='resumennomina',
            name='moneda',
            field=models.CharField(choices=[('COP', 'Peso colombiano'), ('USD', 'Dólar estadounidense'), ('EUR', 'Euro'), ('MXN', 'Peso mexicano'), ('ARS', 'Peso argentino'), ('BRL', 'Real brasileño'), ('CLP', 'Peso chileno'), ('PEN', 'Sol peruano'), ('BOB', 'Boliviano'), ('VES', 'Bolívar venezolano')], max_length=3),
        ),
    ]
